# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-AxKit-Language-XSP-ObjectTaglib
version:      0.04
version_from: lib/Apache/AxKit/Language/XSP/ObjectTaglib.pm
installdirs:  site
requires:
    AxKit:                         

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
