--- #YAML:1.0
name: Apache-AxKit-Language-XSP-ObjectTaglib
abstract: Helper for OO Taglibs
version: 0.06
version_from: lib/Apache/AxKit/Language/XSP/ObjectTaglib.pm
installdirs: site
license: perl
requires:
  AxKit: 1.62
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
