--- 
abstract: Helper for OO Taglibs
author: 
  - Christopher H. Laco
distribution_type: module
generated_by: Module::Install version 0.68
license: artistic
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Apache-AxKit-Language-XSP-ObjectTaglib
no_index: 
  directory: 
    - inc
    - t
requires: 
  AxKit: 1.62
  perl: 5.8.0
tests: t/*.t
version: 0.09000
