--- #YAML:1.0
name:				Apache-AxKit-Language-XSP-ObjectTaglib
version:			0.05
version_from:		lib/Apache/AxKit/Language/XSP/ObjectTaglib.pm
installdirs:		site
requires:
    AxKit:    		1.62
distribution_type:	module
generated_by:		ExtUtils::MakeMaker version 6.17
